/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_metadata_free(a: number): void;
export function __wbg_get_metadata_height(a: number): number;
export function __wbg_set_metadata_height(a: number, b: number): void;
export function __wbg_get_metadata_length(a: number): number;
export function __wbg_set_metadata_length(a: number, b: number): void;
export function __wbg_get_metadata_weight(a: number): number;
export function __wbg_set_metadata_weight(a: number, b: number): void;
export function __wbg_get_metadata_size_variance(a: number): number;
export function __wbg_set_metadata_size_variance(a: number, b: number): void;
export function __wbg_get_metadata_iq(a: number): number;
export function __wbg_set_metadata_iq(a: number, b: number): void;
export function __wbg_get_metadata_core_temp(a: number): number;
export function __wbg_set_metadata_core_temp(a: number, b: number): void;
export function __wbg_get_metadata_stability(a: number): number;
export function __wbg_set_metadata_stability(a: number, b: number): void;
export function __wbg_get_metadata_prevalence(a: number): number;
export function __wbg_set_metadata_prevalence(a: number, b: number): void;
export function __wbg_get_metadata_constancy(a: number): number;
export function __wbg_set_metadata_constancy(a: number, b: number): void;
export function __wbg_get_metadata_longevity(a: number): number;
export function __wbg_set_metadata_longevity(a: number, b: number): void;
export function __wbg_get_metadata_no_appearing(a: number): number;
export function __wbg_set_metadata_no_appearing(a: number, b: number): void;
export function width(): number;
export function height(): number;
export function render_stranger(): number;
export function metadata_new(): number;
export function metadata_class_t(a: number, b: number): void;
export function metadata_disposition(a: number, b: number): void;
export function metadata_vision(a: number, b: number): void;
export function metadata_language_family(a: number, b: number): void;
export function getCurvePoints(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number): void;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
